// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BankDirectDebitApi.Models
{
    [Index("MappingStatusShow01Id", "DeliverStatusId", "BankDirectDebitStatusDisplayId", "BankDirectDebitStatusId", Name = "NonClusteredIndex-20181002-170659")]
    public partial class BankDirectDebitStatus
    {
        [Key]
        public int BankDirectDebitStatusId { get; set; }
        [Column("BankDirectDebitStatus")]
        [StringLength(200)]
        public string BankDirectDebitStatus1 { get; set; }
        public bool? IsActive { get; set; }
        public int? BankDirectDebitStatusDisplayId { get; set; }
        [StringLength(50)]
        public string BankDirectDebitStatusDisplay { get; set; }
        public int? DeliverStatusId { get; set; }
        [StringLength(200)]
        public string MappingStatusShow01 { get; set; }
        public int? MappingStatusShow01Id { get; set; }
    }
}