// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BankDirectDebitApi.Models
{
    [Index("BankId", Name = "I_20181015_1636")]
    [Index("BankDirectDebitStatusId", "BankId", "AccountNo", Name = "NonClusteredIndex-20181003-150655")]
    [Index("BankId", "BankDirectDebitStatusId", "IsActive", Name = "NonClusteredIndex-20190304-0905")]
    public partial class BankDirectDebit
    {
        [Key]
        public int BankDirectDebitId { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string BankId { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string AccountNo { get; set; }
        [StringLength(200)]
        public string AccountName { get; set; }
        public int? BankDirectDebitStatusId { get; set; }
        public int? DDRStandardFormatDetailId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        public int? CreatedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }
        public int? UpdatedByUserId { get; set; }
        public bool? IsActive { get; set; }
        public int? LogId { get; set; }
        /// <summary>
        /// 0 &amp; 9 ผ่าน / 1 ไม่ผ่าน
        /// </summary>
        public int? StatusCode { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ApplyDate { get; set; }
        public int? KTBReportDetailId { get; set; }
        public string CauseText { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Register { get; set; }
        public string Remark { get; set; }
    }
}