// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BankDirectDebitApi.Models
{
    [Keyless]
    public partial class vw_Bank
    {
        public int BankId { get; set; }
        [StringLength(250)]
        public string BankName { get; set; }
        [StringLength(250)]
        public string BankShortName { get; set; }
        [StringLength(3)]
        [Unicode(false)]
        public string BankCode { get; set; }
        public int? SortOrder { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string OrganizeCode { get; set; }
        public bool? IsActive { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedDate { get; set; }
        public int? CreatedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }
        public int? UpdatedByUserId { get; set; }
    }
}