// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using BankDirectDebitApi.Models;

namespace BankDirectDebitApi.Data
{
    public partial class AppDBContext : DbContext
    {
        public AppDBContext()
        {
        }

        public AppDBContext(DbContextOptions<AppDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<BankDirectDebit> BankDirectDebit { get; set; }
        public virtual DbSet<BankDirectDebitStatus> BankDirectDebitStatus { get; set; }
        public virtual DbSet<vw_Bank> vw_Bank { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.UseCollation("Thai_100_CI_AI");

            modelBuilder.Entity<BankDirectDebit>(entity =>
            {
                entity.Property(e => e.StatusCode).HasComment("0 & 9 ผ่าน / 1 ไม่ผ่าน");
            });

            modelBuilder.Entity<vw_Bank>(entity =>
            {
                entity.ToView("vw_Bank");

                entity.Property(e => e.BankId).ValueGeneratedOnAdd();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}